//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealership
{
    using System;
    using System.Collections.Generic;
    
    public partial class iiCars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public iiCars()
        {
            this.iiOrders = new HashSet<iiOrders>();
        }
    
        public int id { get; set; }
        public string vin { get; set; }
        public int mileage { get; set; }
        public int price { get; set; }
        public string photo_path { get; set; }
        public int id_color { get; set; }
        public int id_model { get; set; }
        public int id_status { get; set; }
    
        public virtual iiColors iiColors { get; set; }
        public virtual iiStatus_car iiStatus_car { get; set; }
        public virtual iiModels iiModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iiOrders> iiOrders { get; set; }
    }
}
