//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealership
{
    using System;
    using System.Collections.Generic;
    
    public partial class iiOrders
    {
        public int id { get; set; }
        public System.DateTime order_date { get; set; }
        public int price { get; set; }
        public int id_car { get; set; }
        public int id_status { get; set; }
        public int id_client { get; set; }
        public int id_manager { get; set; }
    
        public virtual iiCars iiCars { get; set; }
        public virtual iiStatus_order iiStatus_order { get; set; }
        public virtual iiUsers iiUsers { get; set; }
        public virtual iiUsers iiUsers1 { get; set; }
    }
}
