//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealership
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user100_dbEntities : DbContext
    {
        public user100_dbEntities()
            : base("name=user100_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<iiColors> iiColors { get; set; }
        public virtual DbSet<iiMakes> iiMakes { get; set; }
        public virtual DbSet<iiPrestige> iiPrestige { get; set; }
        public virtual DbSet<iiRoles> iiRoles { get; set; }
        public virtual DbSet<iiStatus_car> iiStatus_car { get; set; }
        public virtual DbSet<iiStatus_order> iiStatus_order { get; set; }
        public virtual DbSet<iiUsers> iiUsers { get; set; }
        public virtual DbSet<iiCars> iiCars { get; set; }
        public virtual DbSet<iiModels> iiModels { get; set; }
        public virtual DbSet<iiOrders> iiOrders { get; set; }
    }
}
